spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/?useUnicode=true&autoReconnect=true&useSSL=false&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
  jpa:
    open-in-view: false

xrp:
  url: http://localhost:51234/
  test: true

crypto:
  ip: http://127.0.0.1
  port: 9050

logging:
  config: classpath:config/log4j2-local.xml