spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    master:
      url: jdbc:mysql://127.0.0.1:3306/world?useUnicode=true&autoReconnect=true&useSSL=false&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      username: root
      password: root
    slave:
      url: jdbc:mysql://127.0.0.1:3306/world?useUnicode=true&autoReconnect=true&useSSL=false&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      username: root
      password: root
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
  jpa:
    open-in-view: false
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false

xrp:
  url: http://127.0.0.1:51234/
  test: true

crypto:
  ip: http://127.0.0.1
  port: 9050

security:
    option: upsign

logging:
  config: classpath:config/log4j2-local.xml