spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/?useUnicode=true&autoReconnect=true&useSSL=false&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

xrp:
  url: http://localhost:51234/
#  url : https://s.altnet.rippletest.net:51234/
  test: true
